'use client'
import { useEffect, useState } from 'react'
import { getSurvey, clearSurvey } from '@/lib/survey-store'

function generateCompletionCode(participantId: string): string {
  const hex = participantId.replace(/-/g, '').toUpperCase()
  return `${hex.slice(0, 4)}-${hex.slice(4, 8)}-${hex.slice(8, 12)}`
}

export default function CompletePage() {
  const [code, setCode] = useState('')
  const [copied, setCopied] = useState(false)

  useEffect(() => {
    const { participant_id } = getSurvey()
    if (participant_id) {
      setCode(generateCompletionCode(participant_id))
    }
    clearSurvey()
  }, [])

  function copyCode() {
    navigator.clipboard.writeText(code).then(() => {
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    })
  }

  const DEBRIEF = `WHAT THIS STUDY WAS ABOUT

This study examined whether AI-generated explanations from autonomous vehicles affect passenger trust and understanding of vehicle decisions.

You were shown a VLM-Descriptive explanation overlaid on the driving clip. This explanation was generated by GPT-4o analyzing video frames from the CARLA simulator.

Important note: These explanations are post-hoc descriptions — they describe what likely happened, not a direct readout of the vehicle's internal decision process. This is a known limitation of current XAI systems and will be reported in our research.`

  return (
    <div className="min-h-screen bg-gray-50 py-10 px-4">
      <div className="max-w-2xl mx-auto space-y-6">
        <div className="card space-y-6">
          <h1 className="text-2xl font-semibold text-gray-900">Thank You for Participating</h1>

          {/* Completion code */}
          <div className="bg-blue-50 border border-blue-200 rounded-xl p-6 text-center space-y-3">
            <p className="text-sm font-medium text-blue-800">Your Completion Code</p>
            <p className="text-3xl font-mono font-bold tracking-widest text-blue-900">{code || '…'}</p>
            <button
              onClick={copyCode}
              className="px-4 py-2 bg-blue-600 text-white text-sm font-medium rounded-lg
                         hover:bg-blue-700 transition-colors"
            >
              {copied ? 'Copied!' : 'Copy Code'}
            </button>
            <p className="text-xs text-blue-600">
              Please copy this code to confirm your participation.
            </p>
          </div>

          <hr className="border-gray-200" />

          {/* Debrief */}
          <div>
            <h2 className="text-base font-semibold text-gray-800 mb-3">Study Debrief</h2>
            <pre className="whitespace-pre-wrap font-sans text-sm text-gray-600 leading-relaxed">
              {DEBRIEF}
            </pre>
          </div>

          <hr className="border-gray-200" />

          {/* Data withdrawal */}
          <div className="space-y-2">
            <h2 className="text-base font-semibold text-gray-800">Your Right to Withdraw Data</h2>
            <p className="text-sm text-gray-600">
              Now that you know the full purpose, you may withdraw your responses. To do so email:
            </p>
            <p className="text-sm font-medium text-blue-700">
              [your.email@northeastern.edu]
            </p>
            <p className="text-sm text-gray-500">
              Subject: <em>"Data Withdrawal"</em>
            </p>
            <p className="text-sm text-gray-500">
              within 48 hours. Otherwise your anonymized responses will be included in the analysis.
            </p>
          </div>

          <hr className="border-gray-200" />

          {/* Contact */}
          <div className="text-sm text-gray-500 space-y-1">
            <p className="font-medium text-gray-700">Contact</p>
            <p>PI: Yash Phalle &amp; Meet Jain — Northeastern University</p>
            <p>Email: [your.email@northeastern.edu]</p>
            <p>IRB Protocol #: [XXXX]</p>
          </div>
        </div>
      </div>
    </div>
  )
}
