'use client'
import { useEffect, useState } from 'react'
import { getSurvey, clearSurvey } from '@/lib/survey-store'

function generateCompletionCode(participantId: string): string {
  const hex = participantId.replace(/-/g, '').toUpperCase()
  return `${hex.slice(0, 4)}-${hex.slice(4, 8)}-${hex.slice(8, 12)}`
}

export default function CompletePage() {
  const [code, setCode] = useState('')
  const [copied, setCopied] = useState(false)

  const [conditionLabel, setConditionLabel] = useState('')

  const CONDITION_DESCRIPTIONS: Record<string, string> = {
    none:             'no AI-generated explanation (control condition)',
    template:         'a template-based text description generated from rule-based mappings',
    vlm_descriptive:  'a descriptive AI-generated explanation (GPT-4o analyzing the video frames)',
    vlm_teleological: 'a teleological AI-generated explanation describing the vehicle\'s goal and intent',
  }

  useEffect(() => {
    const { participant_id, condition } = getSurvey()
    if (participant_id) {
      setCode(generateCompletionCode(participant_id))
    }
    setConditionLabel(CONDITION_DESCRIPTIONS[condition ?? ''] ?? 'an explanation')
    clearSurvey()
  }, [])

  function copyCode() {
    navigator.clipboard.writeText(code).then(() => {
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    })
  }

  const DEBRIEF = `WHAT THIS STUDY WAS ABOUT

We are studying whether explanations of autonomous vehicle decisions help passengers understand and trust the vehicle more appropriately.

You were shown ${conditionLabel} with each clip. The explanations were generated by GPT-4o analyzing frames from the CARLA driving simulator.

Note: These explanations describe what the vehicle likely perceived. They are not a direct readout from the vehicle's internal systems. We will discuss this limitation in our paper.

Different participants saw different types of explanations. Your responses help us compare how each type affects trust and understanding.`

  return (
    <div className="min-h-screen bg-gray-50 py-10 px-4">
      <div className="max-w-2xl mx-auto space-y-6">
        <div className="card space-y-6">
          <h1 className="text-2xl font-semibold text-gray-900">Thank You for Participating</h1>

          {/* Completion code */}
          <div className="bg-blue-50 border border-blue-200 rounded-xl p-6 text-center space-y-3">
            <p className="text-sm font-medium text-blue-800">Your Completion Code</p>
            <p className="text-3xl font-mono font-bold tracking-widest text-blue-900">{code || '…'}</p>
            <button
              onClick={copyCode}
              className="px-4 py-2 bg-blue-600 text-white text-sm font-medium rounded-lg
                         hover:bg-blue-700 transition-colors"
            >
              {copied ? 'Copied!' : 'Copy Code'}
            </button>
            <p className="text-xs text-blue-600">
              Please copy this code to confirm your participation.
            </p>
          </div>

          <hr className="border-gray-200" />

          {/* Debrief */}
          <div>
            <h2 className="text-base font-semibold text-gray-800 mb-3">Study Debrief</h2>
            <pre className="whitespace-pre-wrap font-sans text-sm text-gray-600 leading-relaxed">
              {DEBRIEF}
            </pre>
          </div>

          <hr className="border-gray-200" />

          {/* Data withdrawal */}
          <div className="space-y-2">
            <h2 className="text-base font-semibold text-gray-800">Your Right to Withdraw Data</h2>
            <p className="text-sm text-gray-600">
              Now that you know the full purpose, you may withdraw your responses. To do so, email us within 48 hours:
            </p>
            <p className="text-sm font-medium text-blue-700">
              phalle.y@northeastern.edu or jain.meet@northeastern.edu
            </p>
            <p className="text-sm text-gray-500">
              Subject: <em>"Data Withdrawal"</em>
            </p>
            <p className="text-sm text-gray-500">
              Otherwise your anonymized responses will be included in the analysis.
            </p>
          </div>

          <hr className="border-gray-200" />

          {/* Contact */}
          <div className="text-sm text-gray-500 space-y-1">
            <p className="font-medium text-gray-700">Contact</p>
            <p>Yash Phalle and Meet Jain, Northeastern University</p>
            <p>phalle.y@northeastern.edu / jain.meet@northeastern.edu</p>
            <p>IRB Protocol #: [XXXX]</p>
          </div>
        </div>
      </div>
    </div>
  )
}
