'use client'
import { useEffect, useState } from 'react'
import { getSurvey, clearSurvey } from '@/lib/survey-store'
import { getConditionForScenario, SCENARIOS } from '@/lib/scenarios'

const CONDITION_LABELS: Record<string, string> = {
  none:             'no explanation (control)',
  vlm_descriptive:  'a descriptive AI explanation',
  vlm_teleological: 'a teleological AI explanation (describing the vehicle\'s goal)',
}

export default function CompletePage() {
  const [conditionSummary, setConditionSummary] = useState('')

  useEffect(() => {
    const survey = getSurvey()
    const groupNumber  = survey.group_number  ?? 0
    const scenarioOrder = survey.scenario_order ?? [0, 1, 2, 3, 4]
    const lines = scenarioOrder.map((scenarioIdx, displaySlot) => {
      const scenario  = SCENARIOS[scenarioIdx]
      const condition = getConditionForScenario(groupNumber, displaySlot)
      return `Clip ${displaySlot + 1} (${scenario?.label ?? scenarioIdx}): ${CONDITION_LABELS[condition] ?? condition}`
    })
    setConditionSummary(lines.join('\n'))
    clearSurvey()
  }, [])

  return (
    <div className="min-h-screen bg-gray-50 py-10 px-4">
      <div className="max-w-2xl mx-auto space-y-5">

        {/* Green confirmation header */}
        <div className="bg-white border border-green-200 rounded-2xl p-8 text-center shadow-sm space-y-4">
          <div className="flex justify-center">
            <div className="w-16 h-16 rounded-full bg-green-100 flex items-center justify-center">
              <svg className="w-8 h-8 text-green-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
              </svg>
            </div>
          </div>
          <h1 className="text-2xl font-semibold text-gray-900">Thank You for Participating</h1>
          <p className="text-sm text-gray-500">Your responses have been recorded. You may now close this tab.</p>
        </div>

        {/* Study debrief */}
        <div className="bg-white border border-gray-200 rounded-2xl p-6 shadow-sm space-y-4">
          <h2 className="text-base font-semibold text-gray-800">What This Study Was About</h2>
          <p className="text-sm text-gray-600 leading-relaxed">
            We are studying whether explanations of autonomous vehicle decisions help passengers understand and trust the vehicle more appropriately.
          </p>
          {conditionSummary && (
            <div className="bg-gray-50 rounded-xl p-4 space-y-1">
              <p className="text-xs font-medium text-gray-500 mb-2">You saw the following explanation types across the 5 clips:</p>
              {conditionSummary.split('\n').map((line, i) => (
                <p key={i} className="text-xs text-gray-600 font-mono">{line}</p>
              ))}
            </div>
          )}
          <p className="text-sm text-gray-600 leading-relaxed">
            The explanations were generated by GPT-4o analyzing frames from the CARLA driving simulator. Different participants saw explanations in a different order. Your responses help us compare how each explanation type affects trust and understanding.
          </p>
        </div>

        {/* Data withdrawal */}
        <div className="bg-white border border-gray-200 rounded-2xl p-6 shadow-sm space-y-2">
          <h2 className="text-base font-semibold text-gray-800">Your Right to Withdraw Data</h2>
          <p className="text-sm text-gray-600">
            Now that you know the full purpose, you may withdraw your responses. Email us within 48 hours:
          </p>
          <p className="text-sm font-medium text-blue-600">phalle.y@northeastern.edu · jain.meet@northeastern.edu</p>
          <p className="text-sm text-gray-500">Subject: <em>"Data Withdrawal"</em></p>
        </div>

        {/* Contact */}
        <div className="text-center text-xs text-gray-400 pb-4 space-y-1">
          <p>Yash Phalle &amp; Meet Jain · Northeastern University</p>
        </div>

      </div>
    </div>
  )
}
